name: Compressed Size

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          filter: kinu
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          install-script: pnpm install --frozen-lockfile --filter kinu
          build-script: 'build:size'
          pattern: '{dist,benchmarks/size/.tmp}/**/*.{js,css}'
